# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/icecube/Projects/EtaStudio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/icecube/Projects/EtaStudio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/icecube/Projects/EtaStudio/CMakeFiles /home/icecube/Projects/EtaStudio//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/icecube/Projects/EtaStudio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EtaStudio

# Build rule for target.
EtaStudio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EtaStudio
.PHONY : EtaStudio

# fast build rule for target.
EtaStudio/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/build
.PHONY : EtaStudio/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

# target to build an object file
cmake_pch.hxx.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

lib/vkbootstrap/VkBootstrap.o: lib/vkbootstrap/VkBootstrap.cpp.o
.PHONY : lib/vkbootstrap/VkBootstrap.o

# target to build an object file
lib/vkbootstrap/VkBootstrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/lib/vkbootstrap/VkBootstrap.cpp.o
.PHONY : lib/vkbootstrap/VkBootstrap.cpp.o

lib/vkbootstrap/VkBootstrap.i: lib/vkbootstrap/VkBootstrap.cpp.i
.PHONY : lib/vkbootstrap/VkBootstrap.i

# target to preprocess a source file
lib/vkbootstrap/VkBootstrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/lib/vkbootstrap/VkBootstrap.cpp.i
.PHONY : lib/vkbootstrap/VkBootstrap.cpp.i

lib/vkbootstrap/VkBootstrap.s: lib/vkbootstrap/VkBootstrap.cpp.s
.PHONY : lib/vkbootstrap/VkBootstrap.s

# target to generate assembly for a file
lib/vkbootstrap/VkBootstrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/lib/vkbootstrap/VkBootstrap.cpp.s
.PHONY : lib/vkbootstrap/VkBootstrap.cpp.s

src/eta_bindings.o: src/eta_bindings.cpp.o
.PHONY : src/eta_bindings.o

# target to build an object file
src/eta_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_bindings.cpp.o
.PHONY : src/eta_bindings.cpp.o

src/eta_bindings.i: src/eta_bindings.cpp.i
.PHONY : src/eta_bindings.i

# target to preprocess a source file
src/eta_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_bindings.cpp.i
.PHONY : src/eta_bindings.cpp.i

src/eta_bindings.s: src/eta_bindings.cpp.s
.PHONY : src/eta_bindings.s

# target to generate assembly for a file
src/eta_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_bindings.cpp.s
.PHONY : src/eta_bindings.cpp.s

src/eta_descriptor.o: src/eta_descriptor.cpp.o
.PHONY : src/eta_descriptor.o

# target to build an object file
src/eta_descriptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_descriptor.cpp.o
.PHONY : src/eta_descriptor.cpp.o

src/eta_descriptor.i: src/eta_descriptor.cpp.i
.PHONY : src/eta_descriptor.i

# target to preprocess a source file
src/eta_descriptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_descriptor.cpp.i
.PHONY : src/eta_descriptor.cpp.i

src/eta_descriptor.s: src/eta_descriptor.cpp.s
.PHONY : src/eta_descriptor.s

# target to generate assembly for a file
src/eta_descriptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_descriptor.cpp.s
.PHONY : src/eta_descriptor.cpp.s

src/eta_device.o: src/eta_device.cpp.o
.PHONY : src/eta_device.o

# target to build an object file
src/eta_device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_device.cpp.o
.PHONY : src/eta_device.cpp.o

src/eta_device.i: src/eta_device.cpp.i
.PHONY : src/eta_device.i

# target to preprocess a source file
src/eta_device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_device.cpp.i
.PHONY : src/eta_device.cpp.i

src/eta_device.s: src/eta_device.cpp.s
.PHONY : src/eta_device.s

# target to generate assembly for a file
src/eta_device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_device.cpp.s
.PHONY : src/eta_device.cpp.s

src/eta_engine.o: src/eta_engine.cpp.o
.PHONY : src/eta_engine.o

# target to build an object file
src/eta_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_engine.cpp.o
.PHONY : src/eta_engine.cpp.o

src/eta_engine.i: src/eta_engine.cpp.i
.PHONY : src/eta_engine.i

# target to preprocess a source file
src/eta_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_engine.cpp.i
.PHONY : src/eta_engine.cpp.i

src/eta_engine.s: src/eta_engine.cpp.s
.PHONY : src/eta_engine.s

# target to generate assembly for a file
src/eta_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_engine.cpp.s
.PHONY : src/eta_engine.cpp.s

src/eta_graphics_pipeline.o: src/eta_graphics_pipeline.cpp.o
.PHONY : src/eta_graphics_pipeline.o

# target to build an object file
src/eta_graphics_pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_graphics_pipeline.cpp.o
.PHONY : src/eta_graphics_pipeline.cpp.o

src/eta_graphics_pipeline.i: src/eta_graphics_pipeline.cpp.i
.PHONY : src/eta_graphics_pipeline.i

# target to preprocess a source file
src/eta_graphics_pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_graphics_pipeline.cpp.i
.PHONY : src/eta_graphics_pipeline.cpp.i

src/eta_graphics_pipeline.s: src/eta_graphics_pipeline.cpp.s
.PHONY : src/eta_graphics_pipeline.s

# target to generate assembly for a file
src/eta_graphics_pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_graphics_pipeline.cpp.s
.PHONY : src/eta_graphics_pipeline.cpp.s

src/eta_material.o: src/eta_material.cpp.o
.PHONY : src/eta_material.o

# target to build an object file
src/eta_material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_material.cpp.o
.PHONY : src/eta_material.cpp.o

src/eta_material.i: src/eta_material.cpp.i
.PHONY : src/eta_material.i

# target to preprocess a source file
src/eta_material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_material.cpp.i
.PHONY : src/eta_material.cpp.i

src/eta_material.s: src/eta_material.cpp.s
.PHONY : src/eta_material.s

# target to generate assembly for a file
src/eta_material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_material.cpp.s
.PHONY : src/eta_material.cpp.s

src/eta_mesh.o: src/eta_mesh.cpp.o
.PHONY : src/eta_mesh.o

# target to build an object file
src/eta_mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_mesh.cpp.o
.PHONY : src/eta_mesh.cpp.o

src/eta_mesh.i: src/eta_mesh.cpp.i
.PHONY : src/eta_mesh.i

# target to preprocess a source file
src/eta_mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_mesh.cpp.i
.PHONY : src/eta_mesh.cpp.i

src/eta_mesh.s: src/eta_mesh.cpp.s
.PHONY : src/eta_mesh.s

# target to generate assembly for a file
src/eta_mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_mesh.cpp.s
.PHONY : src/eta_mesh.cpp.s

src/eta_pipeline.o: src/eta_pipeline.cpp.o
.PHONY : src/eta_pipeline.o

# target to build an object file
src/eta_pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_pipeline.cpp.o
.PHONY : src/eta_pipeline.cpp.o

src/eta_pipeline.i: src/eta_pipeline.cpp.i
.PHONY : src/eta_pipeline.i

# target to preprocess a source file
src/eta_pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_pipeline.cpp.i
.PHONY : src/eta_pipeline.cpp.i

src/eta_pipeline.s: src/eta_pipeline.cpp.s
.PHONY : src/eta_pipeline.s

# target to generate assembly for a file
src/eta_pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_pipeline.cpp.s
.PHONY : src/eta_pipeline.cpp.s

src/eta_swapchain.o: src/eta_swapchain.cpp.o
.PHONY : src/eta_swapchain.o

# target to build an object file
src/eta_swapchain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_swapchain.cpp.o
.PHONY : src/eta_swapchain.cpp.o

src/eta_swapchain.i: src/eta_swapchain.cpp.i
.PHONY : src/eta_swapchain.i

# target to preprocess a source file
src/eta_swapchain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_swapchain.cpp.i
.PHONY : src/eta_swapchain.cpp.i

src/eta_swapchain.s: src/eta_swapchain.cpp.s
.PHONY : src/eta_swapchain.s

# target to generate assembly for a file
src/eta_swapchain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_swapchain.cpp.s
.PHONY : src/eta_swapchain.cpp.s

src/eta_system.o: src/eta_system.cpp.o
.PHONY : src/eta_system.o

# target to build an object file
src/eta_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_system.cpp.o
.PHONY : src/eta_system.cpp.o

src/eta_system.i: src/eta_system.cpp.i
.PHONY : src/eta_system.i

# target to preprocess a source file
src/eta_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_system.cpp.i
.PHONY : src/eta_system.cpp.i

src/eta_system.s: src/eta_system.cpp.s
.PHONY : src/eta_system.s

# target to generate assembly for a file
src/eta_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_system.cpp.s
.PHONY : src/eta_system.cpp.s

src/eta_texture.o: src/eta_texture.cpp.o
.PHONY : src/eta_texture.o

# target to build an object file
src/eta_texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_texture.cpp.o
.PHONY : src/eta_texture.cpp.o

src/eta_texture.i: src/eta_texture.cpp.i
.PHONY : src/eta_texture.i

# target to preprocess a source file
src/eta_texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_texture.cpp.i
.PHONY : src/eta_texture.cpp.i

src/eta_texture.s: src/eta_texture.cpp.s
.PHONY : src/eta_texture.s

# target to generate assembly for a file
src/eta_texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/eta_texture.cpp.s
.PHONY : src/eta_texture.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EtaStudio.dir/build.make CMakeFiles/EtaStudio.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shaders"
	@echo "... EtaStudio"
	@echo "... cmake_pch.hxx.gch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
	@echo "... lib/vkbootstrap/VkBootstrap.o"
	@echo "... lib/vkbootstrap/VkBootstrap.i"
	@echo "... lib/vkbootstrap/VkBootstrap.s"
	@echo "... src/eta_bindings.o"
	@echo "... src/eta_bindings.i"
	@echo "... src/eta_bindings.s"
	@echo "... src/eta_descriptor.o"
	@echo "... src/eta_descriptor.i"
	@echo "... src/eta_descriptor.s"
	@echo "... src/eta_device.o"
	@echo "... src/eta_device.i"
	@echo "... src/eta_device.s"
	@echo "... src/eta_engine.o"
	@echo "... src/eta_engine.i"
	@echo "... src/eta_engine.s"
	@echo "... src/eta_graphics_pipeline.o"
	@echo "... src/eta_graphics_pipeline.i"
	@echo "... src/eta_graphics_pipeline.s"
	@echo "... src/eta_material.o"
	@echo "... src/eta_material.i"
	@echo "... src/eta_material.s"
	@echo "... src/eta_mesh.o"
	@echo "... src/eta_mesh.i"
	@echo "... src/eta_mesh.s"
	@echo "... src/eta_pipeline.o"
	@echo "... src/eta_pipeline.i"
	@echo "... src/eta_pipeline.s"
	@echo "... src/eta_swapchain.o"
	@echo "... src/eta_swapchain.i"
	@echo "... src/eta_swapchain.s"
	@echo "... src/eta_system.o"
	@echo "... src/eta_system.i"
	@echo "... src/eta_system.s"
	@echo "... src/eta_texture.o"
	@echo "... src/eta_texture.i"
	@echo "... src/eta_texture.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

